(require 'asdf)
(asdf:load-asd (truename "clad.asd"))
(asdf:load-system :clad/tests)

;; Run just the vertices query test
(format t "~%Running vertices test...~%")
(let* ((core-box (clad.core:make-box 100 50 30))
       (cad-box (clad.shapes:wrap-shape core-box 'clad.shapes:cad-solid)))
  (let ((vertex-list (clad.shapes:vertices cad-box)))
    (format t "Vertex list length: ~A~%" (length vertex-list))
    (format t "Expected: 8~%")
    (format t "Match: ~A~%" (= (length vertex-list) 8))))

(format t "~%Running edges test...~%")
(let* ((core-box (clad.core:make-box 100 50 30))
       (cad-box (clad.shapes:wrap-shape core-box 'clad.shapes:cad-solid)))
  (let ((edge-list (clad.shapes:edges cad-box)))
    (format t "Edge list length: ~A~%" (length edge-list))
    (format t "Expected: 12~%")
    (format t "Match: ~A~%" (= (length edge-list) 12))))
